package com.acolonia.spring.frontend.model.enums;

public enum RoleCategory {
    CAPACITACION,
    VIAJES,
    SUMINISTROS_DE_OFICINA,
    MANTENIMIENTO,
    SERVICIOS_EXTERNOS,
    OPERATIVO,
    PAPELERIA,
    TRANSPORTE_LOCAL,
    REPARACIONES_MENORES,
    SERVICIOS_MENSAJERIA,
    REEMBOLSOS_VARIOS;
}
